ARG APP_IMAGE=balenalib/armv7hf-debian:buster
FROM $APP_IMAGE

COPY . /kivy

RUN [ "cross-build-start" ]

# Get apt-get dependencies.
RUN apt-get update
RUN apt-get -y install apt-utils
RUN apt-get -y install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev
RUN apt-get -y install libgstreamer1.0-dev gstreamer1.0-alsa gstreamer1.0-plugins-base
RUN apt-get -y install python3-dev libsmpeg-dev libswscale-dev libavformat-dev libavcodec-dev libjpeg-dev libtiff5-dev libx11-dev libmtdev-dev
RUN apt-get -y install python3-setuptools build-essential libgl1-mesa-dev libgles2-mesa-dev
RUN apt-get -y install xvfb pulseaudio xsel
RUN apt-get -y install python3-pip

# Get Python dependencies
RUN python3 -m pip install -U pip setuptools wheel
ARG CYTHON_INSTALL=0.29.10
RUN python3 -m pip install -U docutils Cython=="$CYTHON_INSTALL"

# Build the wheel.
RUN export VIDEOCOREMESA=1; python3 -m pip -v wheel --build=/kivy-build --wheel-dir=/kivy-wheel /kivy

# Make sure the wheel is working.
RUN python3 -m pip install --find-links=/kivy-wheel kivy
RUN python3 -c "import kivy; print(dir(kivy))"

RUN [ "cross-build-end" ]
